using IntegratedProjectManagementSystem.Inventory;
using IntegratedProjectManagementSystem.Resources;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace IntegratedProjectManagementSystem.Dashboard
{
    public partial class FormDashboard : Form
    {
        public FormDashboard()
        {
            InitializeComponent();
        }

        ///SAMPLE PDF GENERATION USING QUESTPDF
        private void button1_Click(object sender, EventArgs e)
        {

            String text = txtBox.Text;

            using (SaveFileDialog saveFileDialog = new SaveFileDialog())
            {
                saveFileDialog.Filter = "PDF files (*.pdf)|*.pdf";
                saveFileDialog.Title = "Save PDF File";
                saveFileDialog.FileName = "document.pdf";

                if (saveFileDialog.ShowDialog() == DialogResult.OK)
                {
                    QuestPDF.Settings.License = LicenseType.Community;

                    var document = Document.Create(container =>
                    {
                        container.Page(page =>
                        {
                            page.Size(PageSizes.A4);
                            page.Margin(2, Unit.Centimetre);
                            page.PageColor(Colors.White);
                            page.DefaultTextStyle(x => x.FontSize(20));

                            page.Header()
                                .Text("Hello QuestPDF!")
                                .SemiBold().FontSize(36).FontColor(Colors.Blue.Medium);

                            page.Content()
                                .PaddingVertical(1, Unit.Centimetre)
                                .Column(x =>
                                {
                                    x.Spacing(20);
                                    x.Item().Text("This is a sample PDF generated by QuestPDF");
                                    x.Item().Text(DateTime.Now.ToString("MMMM dd, yyyy"));
                                    x.Item().Text(txtBox.Text);
                                });

                            page.Footer()
                                .AlignCenter()
                                .Text(x =>
                                {
                                    x.Span("Page ");
                                    x.CurrentPageNumber();
                                });
                        });
                    });

                    document.GeneratePdf(saveFileDialog.FileName);
                    MessageBox.Show($"PDF saved successfully at {saveFileDialog.FileName}");
                }
            }
        }

        private void btnDashboard_Click(object sender, EventArgs e)
        {
            HelperNavigation.OpenForm<FormDashboard>(this);
        }
        private void btnInventory_Click(object sender, EventArgs e)
        {
            HelperNavigation.OpenForm<FormInventory>(this);
        }

        private void btnLogout_Click(object sender, EventArgs e)
        {
            HelperNavigation.ReturnToLogin(this);
        }
    }
}
